name: test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  windows-build-test:
    runs-on: windows-2019

    env:
      CXXFLAGS: /MP

    steps:

      - name: Check if gflags is available
        shell: pwsh
        run: |
          ls -path C:\* -R -Filter gflags.exe -ErrorAction SilentlyContinue | select -First 4

      - name: Check if cdg is available
        shell: pwsh
        run: |
          ls -path C:\* -R -Filter cdb.exe -ErrorAction SilentlyContinue | select -First 4
